library(shiny)
library(shinydashboard)
library(leaflet)
library(magrittr)
hotpot<-read.csv(file = "~/Desktop/R/Shiny/foodd/hotpot.csv",fileEncoding="BIG5")
steak<-read.csv(file = "~/Desktop/R/Shiny/foodd/steak.csv",fileEncoding="BIG5")
Skewer<-read.csv(file = "~/Desktop/R/Shiny/foodd/Skewer.csv",fileEncoding="BIG5")
dessert<-read.csv(file = "~/Desktop/R/Shiny/foodd/dessert.csv",fileEncoding="BIG5")
cafe<-read.csv(file = "~/Desktop/R/Shiny/foodd/cafe.csv",fileEncoding="BIG5")
brunch<-read.csv(file = "~/Desktop/R/Shiny/foodd/brunch.txt",fileEncoding="BIG5")
afternoon<-read.csv(file = "~/Desktop/R/Shiny/foodd/afternoon.csv",fileEncoding="BIG5")
japan<-read.csv(file = "~/Desktop/R/Shiny/foodd/japan.csv",fileEncoding="BIG5")
usa<-read.csv(file = "~/Desktop/R/Shiny/foodd/usa.csv",fileEncoding="BIG5")
seafood<-read.csv(file = "~/Desktop/R/Shiny/foodd/seafood.csv",fileEncoding="BIG5")
